name: Pull Request

on:
  workflow_dispatch:
  push:
    paths:
      - "apps/**"
      - "bindings/**"
      - "include/**"
      - "src/**"
      - "test/**"
    branches: [main]
  pull_request:
    paths:
      - ".github/**"
      - "apps/**"
      - "bindings/**"
      - "include/**"
      - "src/**"
      - "test/**"
    branches: [main]

env:
  TARGET: Release

jobs:
  build_and_test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name:
          [
            "ubuntu-18.04-gcc-9.3.0",
            "ubuntu-18.04-clang-10.0.0",
            "macos-10.15-xcode-12.0",
            "windows-2019-gcc-9.2.0",
          ]
        include:
          - name: ubuntu-18.04-gcc-9.3.0
            os: ubuntu-18.04
            compiler: gcc
            version: "9"
          - name: ubuntu-18.04-clang-10.0.0
            os: ubuntu-18.04
            compiler: clang
            version: "10"
          - name: macOS-10.15-xcode-12.0
            os: macOS-10.15
            compiler: xcode
            version: "12"
          - name: windows-2019-gcc-9.2.0
            os: windows-2019
            compiler: gcc
            version: "9"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Change Directory
        run: cd ${{ github.workspace }}
      - name: Update Environment
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          else
            sudo apt-get install -y clang-${{ matrix.version }} g++-multilib
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi
      - name: Update Environment
        if: runner.os == 'macOS'
        run: |
          ls -ls /Applications/
          ls -ls $ANDROID_SDK_ROOT/ndk
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
      - name: Update Environment
        if: runner.os == 'Windows'
        run: |
          $msyspath="C:\msys64"
          echo "$msyspath\usr\bin" >> $GITHUB_PATH
          echo "$msyspath" >> $GITHUB_PATH
          echo "$msyspath\mingw64\bin" >> $GITHUB_PATH
          echo "$msyspath\mingw64\lib" >> $GITHUB_PATH
          echo "$msyspath\mingw64\include" >> $GITHUB_PATH
      - name: Configure Environment
        run: make environment
      - name: Make Release Build
        if: runner.os == 'Linux'
        env:
          NDK_PATH: $$ANDROID_SDK_ROOT/ndk/21.3.6528147
        run: |
          make build
          # if [ "${{ matrix.compiler }}" = "clang" ]; then
          #   make build-android
          # fi
      - name: Make Release Build
        if: runner.os == 'macOS'
        env:
          NDK_PATH: $$ANDROID_HOME/ndk/21.3.6528147
        run: |
          make build
          # make build-android
          # make build-ios
          # make build-netstandard
      - name: Run Tests
        if: runner.os == 'macOS'
        run: make test
      - name: Run Address Sanitizer
        if: runner.os == 'Linux'
        run: make sanitize-asan
